version: '3'
services:
  database:
    image: mariadb
    environment:
      ...
  wordpress:
    image: wordpress:4.9.7
    depends_on:
      - database
    environment:
      ...
    ports:
      - 8080:80